server:
  port: 8080

spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3306/spring-security-demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8

mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.uwjx.spring.security.auth.server.mapper: debug
