server:
  port: 8081
  servlet:
    context-path: /client-01
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/authServer/oauth/token
      user-authorization-uri: http://localhost:8080/authServer/oauth/authorize
      client-id: client-01
      client-secret: 1123123
    resource:
      token-info-uri: http://localhost:8080/authServer/oauth/check_token
